In [1]:
from scipy.optimize import *
import pandas as pd 
import numpy as np 
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
from pulp import *

In [284]:
a = df.values

set_I = range(0,a.shape[1])

In [285]:
set_I

range(0, 986)

In [2]:
df = pd.read_csv("WeeklyReturns.csv", index_col="Date")

In [4]:

a = df.values

set_I = range(0,a.shape[1])



# Generate proble, & Create variables
prob = LpProblem("numpy_constraints", LpMaximize)
V = pulp.LpVariable.dicts("V", set_I, cat='Int')

# Make up an objective, let's say sum of V_i
prob += 2*lpSum([x*z for x,z in zip(sorted([x/np.sum(np.linalg.eig(np.cov((a*V - np.mean((a*V).T,axis=1)).T))[0]) for x in np.linalg.eig(np.cov((a*V - np.mean((a*V).T,axis=1)).T))[0]], reverse=True),range(1,len(sorted([x/np.sum(np.linalg.eig(np.cov((a*V - np.mean((a*V).T,axis=1)).T))[0]) for x in np.linalg.eig(np.cov((a*V - np.mean((a*V).T,axis=1)).T))[0]], reverse=True))+1,1))])-1

# Apply constraints
prob += lpSum([V[i] for i in set_I]) == 2


# Solve problem
prob.solve()

# Print results:
V_soln = np.array([V[i].varValue for i in set_I])
print (("Status:"), LpStatus[prob.status])
print("V_soln: ")
print(V_soln)

In [101]:
df = pd.read_csv("WeeklyReturns.csv", index_col="Date")

In [278]:
    a =  df.iloc[:,:2].values
    c = (a - np.mean(a.T,axis=1)).T
    var_exp = np.linalg.eig(np.cov((a - np.mean(a.T,axis=1)).T))[0]
    expla = sorted([x/np.sum(var_exp) for x in var_exp], reverse=True)
    pca_cal = -(2*np.sum([x*z for x,z in zip(expla,range(1,len(expla)+1,1))])-1)

In [283]:
expla

[0.9998051494351591, 0.00019485056484092164]

In [279]:
2*np.sum([x*z for x,z in zip(sorted([x/np.sum(np.linalg.eig(np.cov((a - np.mean(a.T,axis=1)).T))[0]) for x in np.linalg.eig(np.cov((a - np.mean(a.T,axis=1)).T))[0]], reverse=True),range(1,len(sorted([x/np.sum(np.linalg.eig(np.cov((a - np.mean(a.T,axis=1)).T))[0]) for x in np.linalg.eig(np.cov((a - np.mean(a.T,axis=1)).T))[0]], reverse=True))+1,1))])-1

1.000389701129682

In [280]:
sorted([x/np.sum(np.linalg.eig(np.cov(np.cov((a - np.mean(a.T,axis=1)).T)))[0]) for x in np.linalg.eig(np.cov(np.cov((a - np.mean(a.T,axis=1)).T)))[0]], reverse=True)

[0.9999999999999999, 6.65970422393554e-17]

In [281]:
    from sklearn.decomposition import PCA
    pca = PCA()
    pca
    corr_matrix = np.array(df.iloc[:,:2].cov())
    principalComponents = pca.fit(corr_matrix)
    pdi = 2*np.sum([x*z for x,z in zip(principalComponents.explained_variance_ratio_,range(1,len(principalComponents.explained_variance_ratio_)+1,1))])-1

In [282]:
pdi

1.0

In [266]:
df.iloc[:,:2].cov()

SPY       IVV
SPY  0.000701  0.000704
IVV  0.000704  0.000708

In [ ]:
def objective(x):
    a =  xo*df.iloc[:,:2].values
    c = a - np.mean(a.T,axis=1)
    var_exp = np.linalg.eig(np.cov(c.T))[0]
    expla = [x/np.sum(var_exp) for x in var_exp]
    pca_cal = -(2*np.sum([x*z for x,z in zip(expla,range(1,len(expla)+1,1))])-1)
    return pca_cal

In [144]:
from sklearn.decomposition import PCA
def objective(x):
    a =  xo*df.iloc[:,:]   
    corr_matrix = np.array(a.cov())
    principalComponents = pca.fit(corr_matrix)
    pdi = -(2*np.sum([x*z for x,z in zip(principalComponents.explained_variance_ratio_,range(1,len(principalComponents.explained_variance_ratio_)+1,1))])-1)

    return pdi
xo = np.ones(len(df.columns), int)

In [150]:
solution = minimize(objective,xo,method="Powell")

KeyboardInterrupt: 

In [145]:
xo = np.ones(len(df.columns), int)
objective(xo)

-1.255722525183272

In [142]:
    from sklearn.decomposition import PCA
    pca = PCA()
    pca
    corr_matrix = np.array(df.iloc[:,:].cov())
    principalComponents = pca.fit(corr_matrix)
    pdi = 2*np.sum([x*z for x,z in zip(principalComponents.explained_variance_ratio_,range(1,len(principalComponents.explained_variance_ratio_)+1,1))])-1

In [143]:
pdi

1.255722525183272

In [115]:
df.iloc[:,:10].cov().values

array([[0.00070106, 0.00070425, 0.00071722, 0.00070165, 0.00070476,
        0.00058708, 0.000584  , 0.000512  , 0.00071484, 0.00053208],
       [0.00070425, 0.00070801, 0.00072058, 0.00070518, 0.00070773,
        0.00058739, 0.00058423, 0.00051215, 0.00071817, 0.00053218],
       [0.00071722, 0.00072058, 0.00073621, 0.00071799, 0.00071949,
        0.00060177, 0.00059854, 0.00052479, 0.00073188, 0.0005451 ],
       [0.00070165, 0.00070518, 0.00071799, 0.00070264, 0.00070552,
        0.00058464, 0.00058137, 0.00051142, 0.00071584, 0.00053153],
       [0.00070476, 0.00070773, 0.00071949, 0.00070552, 0.00079192,
        0.00057015, 0.0005662 , 0.00053613, 0.00075822, 0.00055999],
       [0.00058708, 0.00058739, 0.00060177, 0.00058464, 0.00057015,
        0.0006055 , 0.00060514, 0.00052787, 0.00058807, 0.00055038],
       [0.000584  , 0.00058423, 0.00059854, 0.00058137, 0.0005662 ,
        0.00060514, 0.00060719, 0.0005208 , 0.00058424, 0.00054202],
       [0.000512  , 0.00051215, 0.0005247

In [76]:
dd = np.ones(len(df.columns), int)

In [77]:
df.iloc[:,:].values*dd

array([[ 0.00488211,  0.00471682,  0.00421808, ...,  0.        ,
         0.00348901, -0.01094685],
       [ 0.00128329,  0.00141289,  0.00134078, ...,  0.        ,
        -0.00722118, -0.01660217],
       [ 0.00036646,  0.00050053,  0.00089253, ...,  0.        ,
        -0.00915952, -0.00056262],
       ...,
       [-0.0206376 , -0.02053184, -0.02796826, ..., -0.02694495,
         0.07612455, -0.00948214],
       [ 0.15492151,  0.15484698,  0.16015567, ...,  0.0216887 ,
        -0.31404071, -0.23564064],
       [-0.0128034 , -0.01279648, -0.01054905, ...,  0.01527499,
         0.00546873,  0.05684009]])

In [111]:
    from sklearn.decomposition import PCA
    pca = PCA()
    corr_matrix = df.iloc[:,:10].values
    principalComponents = pca.fit(corr_matrix)

In [112]:
pca.explained_variance_

array([6.23417164e-03, 4.66503705e-04, 1.65298730e-04, 4.98941926e-05,
       6.93980379e-06, 4.01809118e-06, 1.68018836e-06, 7.87365194e-07,
       2.34754394e-07, 9.39823994e-08])

In [33]:

expla = [x/np.sum(var_exp) for x in var_exp]
pca_cal = 2*np.sum(expla*range(1,len(expla)+1,1))-1

TypeError: can't multiply sequence by non-int of type 'range'

In [79]:
print(objective(xo))

(9.423731707275667-1.1774937225412912e-15j)
